import type { FixturePairExpectation, MatcherDevlogInput, MatcherCandidate } from "@/lib/voice-adoption/types";

/** 10-pair precision fixture — devlog covers tutorial, boss HP, UI labels */
export const FIXTURE_DEVLOG: MatcherDevlogInput = {
  id: "fixture-devlog-001",
  projectId: "emberfall",
  title: "v0.2 — チュートリアル追加と序盤調整",
  content:
    "チュートリアルを追加しました。序盤ボスのHPを30%削減し、UIの説明文も整理しました。",
  publishedVersion: "0.2",
  publishedAt: "2026-06-16T10:00:00.000Z",
  createdAt: "2026-06-16T09:00:00.000Z",
};

export const FIXTURE_CANDIDATES: MatcherCandidate[] = [
  {
    voiceResponseId: "fixture-voice-01",
    userId: "fixture-user-a",
    projectId: "emberfall",
    versionKey: "0.1",
    promptText: "改善してほしい点は？",
    answerValue: "tutorial",
    answerLabel: "チュートリアルが欲しい",
    createdAt: "2026-06-10T10:00:00.000Z",
  },
  {
    voiceResponseId: "fixture-voice-02",
    userId: "fixture-user-a",
    projectId: "emberfall",
    versionKey: "0.1",
    promptText: "改善してほしい点は？",
    answerValue: "boss",
    answerLabel: "ボス戦が長すぎる",
    createdAt: "2026-06-11T10:00:00.000Z",
  },
  {
    voiceResponseId: "fixture-voice-03",
    userId: "fixture-user-b",
    projectId: "emberfall",
    versionKey: "0.1",
    promptText: "改善してほしい点は？",
    answerValue: "tutorial_lack",
    answerLabel: "チュートリアル不足",
    createdAt: "2026-06-12T10:00:00.000Z",
  },
  {
    voiceResponseId: "fixture-voice-04",
    userId: "fixture-user-b",
    projectId: "emberfall",
    versionKey: "0.1",
    promptText: "改善してほしい点は？",
    answerValue: "boss_hp",
    answerLabel: "序盤の敵が強すぎる",
    createdAt: "2026-06-12T11:00:00.000Z",
  },
  {
    voiceResponseId: "fixture-voice-05",
    userId: "fixture-user-c",
    projectId: "emberfall",
    versionKey: "0.1",
    promptText: "改善してほしい点は？",
    answerValue: "ui",
    answerLabel: "UIの説明が分かりにくい",
    createdAt: "2026-06-13T10:00:00.000Z",
  },
  {
    voiceResponseId: "fixture-voice-06",
    userId: "fixture-user-c",
    projectId: "emberfall",
    versionKey: "0.1",
    promptText: "改善してほしい点は？",
    answerValue: "bgm",
    answerLabel: "BGMがうるさい",
    createdAt: "2026-06-13T11:00:00.000Z",
  },
  {
    voiceResponseId: "fixture-voice-07",
    userId: "fixture-user-d",
    projectId: "emberfall",
    versionKey: "0.1",
    promptText: "改善してほしい点は？",
    answerValue: "multiplayer",
    answerLabel: "マルチプレイが欲しい",
    createdAt: "2026-06-14T10:00:00.000Z",
  },
  {
    voiceResponseId: "fixture-voice-08",
    userId: "fixture-user-d",
    projectId: "emberfall",
    versionKey: "0.1",
    promptText: "改善してほしい点は？",
    answerValue: "story",
    answerLabel: "ストーリーが短い",
    createdAt: "2026-06-14T11:00:00.000Z",
  },
  {
    voiceResponseId: "fixture-voice-09",
    userId: "fixture-user-e",
    projectId: "emberfall",
    versionKey: "0.1",
    promptText: "改善してほしい点は？",
    answerValue: "game",
    answerLabel: "ゲームは面白い",
    createdAt: "2026-06-15T10:00:00.000Z",
  },
  {
    voiceResponseId: "fixture-voice-10",
    userId: "fixture-user-e",
    projectId: "emberfall",
    versionKey: "0.1",
    promptText: "改善してほしい点は？",
    answerValue: "maybe_tutorial",
    answerLabel: "最初が少し分かりにくいかも",
    createdAt: "2026-06-15T11:00:00.000Z",
  },
];

export const FIXTURE_PAIR_EXPECTATIONS: FixturePairExpectation[] = [
  {
    id: "fixture-voice-01",
    label: "チュートリアルが欲しい",
    playerQuote: "チュートリアルが欲しい",
    updateSummary: "チュートリアルを追加",
    answerKeywords: ["チュートリアル"],
    shouldAdopt: true,
    category: "related",
  },
  {
    id: "fixture-voice-02",
    label: "ボス戦が長すぎる",
    playerQuote: "ボス戦が長すぎる",
    updateSummary: "序盤ボスのHPを30%削減",
    answerKeywords: ["ボス"],
    shouldAdopt: true,
    category: "related",
  },
  {
    id: "fixture-voice-03",
    label: "チュートリアル不足",
    playerQuote: "チュートリアル不足",
    updateSummary: "チュートリアルを追加",
    answerKeywords: ["チュートリアル"],
    shouldAdopt: true,
    category: "related",
  },
  {
    id: "fixture-voice-04",
    label: "序盤の敵が強すぎる",
    playerQuote: "序盤の敵が強すぎる",
    updateSummary: "序盤ボスのHPを30%削減",
    answerKeywords: ["序盤", "敵", "強"],
    shouldAdopt: true,
    category: "related",
  },
  {
    id: "fixture-voice-05",
    label: "UIの説明が分かりにくい",
    playerQuote: "UIの説明が分かりにくい",
    updateSummary: "UIの説明文を整理",
    answerKeywords: ["UI", "説明"],
    shouldAdopt: true,
    category: "related",
  },
  {
    id: "fixture-voice-06",
    label: "BGMがうるさい",
    playerQuote: "BGMがうるさい",
    answerKeywords: ["BGM"],
    shouldAdopt: false,
    category: "unrelated",
  },
  {
    id: "fixture-voice-07",
    label: "マルチプレイが欲しい",
    playerQuote: "マルチプレイが欲しい",
    answerKeywords: ["マルチ"],
    shouldAdopt: false,
    category: "unrelated",
  },
  {
    id: "fixture-voice-08",
    label: "ストーリーが短い",
    playerQuote: "ストーリーが短い",
    answerKeywords: ["ストーリー"],
    shouldAdopt: false,
    category: "unrelated",
  },
  {
    id: "fixture-voice-09",
    label: "ゲームは面白い（称賛）",
    playerQuote: "ゲームは面白い",
    answerKeywords: ["面白"],
    shouldAdopt: false,
    category: "unrelated",
  },
  {
    id: "fixture-voice-10",
    label: "最初が少し分かりにくい（グレー）",
    playerQuote: "最初が少し分かりにくい",
    answerKeywords: ["分かり"],
    shouldAdopt: false,
    category: "grey",
  },
];

export const FIXTURE_PROJECT_TITLE = "Emberfall";
