-- STAGING ONLY — re-apply search_public_catalog from 079 (canonical)
-- Target: vuqpwvjvgyxffmvpfrxo only. Safe to re-run.
-- DO NOT edit this file by hand. Regenerate:
--   node scripts/staging-only/sync-079-search-patch.mjs
--
-- Confirm after apply:
--   SELECT count(*) FROM public.search_public_catalog('zzz-ia-seed-nohit-999', 10);
-- Expect: 0
-- Also spot-check: ローグライク / Unity / ドット絵 / 配信OK

CREATE OR REPLACE FUNCTION public.search_public_catalog(
  p_query text,
  p_limit integer DEFAULT 20
)
RETURNS TABLE (
  result_kind text,
  result_id text,
  title text,
  subtitle text,
  category text,
  thumbnail_url text,
  rank real
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_q text := btrim(coalesce(p_query, ''));
  v_norm text;
  v_limit integer := greatest(1, least(coalesce(p_limit, 20), 40));
  v_terms text[];
BEGIN
  IF char_length(v_q) < 1 THEN
    RETURN;
  END IF;

  v_norm := public.forge_search_normalize(v_q);
  IF char_length(btrim(v_norm)) < 1 THEN
    RETURN;
  END IF;

  v_terms := array_remove(regexp_split_to_array(v_norm, '\s+'), '');

  RETURN QUERY
  WITH project_hits AS (
    SELECT
      'project'::text AS result_kind,
      p.id::text AS result_id,
      p.title AS title,
      coalesce(nullif(btrim(p.creator), ''), nullif(btrim(p.owner_name), ''), '') AS subtitle,
      coalesce(p.category, 'game') AS category,
      p.thumbnail_url AS thumbnail_url,
      (
        similarity(public.forge_project_search_document(p), v_norm)
        + CASE WHEN public.forge_project_search_document(p) LIKE '%' || v_norm || '%' THEN 0.5 ELSE 0 END
        + CASE
            WHEN v_terms <@ string_to_array(public.forge_project_search_document(p), ' ') THEN 0.35
            ELSE 0
          END
      )::real AS rank
    FROM public.projects p
    WHERE p.visibility = 'public'
      AND (
        public.forge_project_search_document(p) LIKE '%' || v_norm || '%'
        OR public.forge_project_search_document(p) % v_norm
        OR EXISTS (
          SELECT 1
          FROM unnest(v_terms) t(term)
          WHERE char_length(t.term) >= 2
            AND public.forge_project_search_document(p) LIKE '%' || t.term || '%'
        )
      )
  ),
  developer_hits AS (
    SELECT
      'developer'::text AS result_kind,
      d.user_id::text AS result_id,
      d.public_name AS title,
      coalesce(nullif(btrim(d.profile), ''), '') AS subtitle,
      NULL::text AS category,
      d.avatar_url AS thumbnail_url,
      (
        similarity(public.forge_developer_search_document(d), v_norm)
        + CASE WHEN public.forge_developer_search_document(d) LIKE '%' || v_norm || '%' THEN 0.5 ELSE 0 END
      )::real AS rank
    FROM public.developer_profiles d
    WHERE EXISTS (
        SELECT 1 FROM public.projects p
        WHERE p.owner_id = d.user_id AND p.visibility = 'public'
      )
      AND (
        public.forge_developer_search_document(d) LIKE '%' || v_norm || '%'
        OR public.forge_developer_search_document(d) % v_norm
        OR EXISTS (
          SELECT 1
          FROM unnest(v_terms) t(term)
          WHERE char_length(t.term) >= 2
            AND public.forge_developer_search_document(d) LIKE '%' || t.term || '%'
        )
      )
  ),
  tag_hits AS (
    -- Tag match = tag contains the full normalized query only
    -- (ドット→ドット絵, Unreal→Unreal Engine, SE→SE).
    -- Do NOT reverse-contain (v_norm LIKE '%'||tag||'%'): that made
    -- "zzz ia seed nohit 999" match tag "SE" via substring "se" inside "seed".
    SELECT
      scored.result_kind,
      scored.result_id,
      scored.title,
      scored.subtitle,
      scored.category,
      scored.thumbnail_url,
      scored.rank
    FROM (
      SELECT DISTINCT ON (tags.tag_value)
        'tag'::text AS result_kind,
        tags.tag_value AS result_id,
        tags.tag_value AS title,
        'タグ'::text AS subtitle,
        NULL::text AS category,
        NULL::text AS thumbnail_url,
        (
          CASE
            WHEN norm.tag_norm = v_norm THEN 0.9
            ELSE 0.55
          END
          + least(similarity(norm.tag_norm, v_norm), 0.2)
        )::real AS rank
      FROM (
        SELECT unnest(coalesce(p.tags, '{}')) AS tag_value
        FROM public.projects p
        WHERE p.visibility = 'public'
        UNION ALL
        SELECT unnest(coalesce(p.purpose_tags, '{}'))
        FROM public.projects p
        WHERE p.visibility = 'public'
        UNION ALL
        SELECT unnest(coalesce(p.genres, '{}'))
        FROM public.projects p
        WHERE p.visibility = 'public'
        UNION ALL
        SELECT unnest(coalesce(d.activity_tags, '{}'))
        FROM public.developer_profiles d
        WHERE EXISTS (
          SELECT 1 FROM public.projects p
          WHERE p.owner_id = d.user_id AND p.visibility = 'public'
        )
      ) tags
      CROSS JOIN LATERAL (
        SELECT public.forge_search_normalize(tags.tag_value) AS tag_norm
      ) norm
      WHERE
        char_length(btrim(v_norm)) >= 1
        AND norm.tag_norm LIKE '%' || v_norm || '%'
        -- Internal ops markers (seed bookkeeping) are not user-facing tag results.
        AND tags.tag_value IS DISTINCT FROM 'forge-ia-seed-v1'
        AND tags.tag_value NOT LIKE 'forge-ia-seed-%'
      ORDER BY tags.tag_value, rank DESC
    ) scored
  )
  SELECT * FROM (
    SELECT * FROM project_hits
    UNION ALL
    SELECT * FROM developer_hits
    UNION ALL
    SELECT * FROM tag_hits
  ) hits
  -- Drop pure-trigram / weak noise; real substring/tag hits score ≥ ~0.35+.
  WHERE hits.rank > 0.2
  ORDER BY hits.rank DESC, hits.title ASC
  LIMIT v_limit;
END;
$$;

REVOKE ALL ON FUNCTION public.search_public_catalog(text, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.search_public_catalog(text, integer)
  TO anon, authenticated, service_role;
