import { buildStagingCase } from "./build-case";
import type { StagingLabeledCase } from "./types";

/** direct 20 — devlog に明示的な対応記述あり */
export const STAGING_DIRECT_CASES: StagingLabeledCase[] = [
  buildStagingCase({
    category: "direct",
    index: 1,
    label: "direct-01 チュートリアル",
    voiceLabel: "チュートリアルが欲しい",
    devlogTitle: "v0.2 — チュートリアル追加",
    devlogContent: "初回プレイ向けのチュートリアルを追加しました。",
    referenceUpdateSummary: "チュートリアルを追加",
  }),
  buildStagingCase({
    category: "direct",
    index: 2,
    label: "direct-02 ボスHP",
    voiceLabel: "序盤ボスが強すぎる",
    devlogTitle: "v0.2 — 序盤ボス調整",
    devlogContent: "序盤ボスのHPを30%削減しました。",
    referenceUpdateSummary: "序盤ボスのHPを30%削減",
  }),
  buildStagingCase({
    category: "direct",
    index: 3,
    label: "direct-03 UI説明",
    voiceLabel: "UIの説明が分かりにくい",
    devlogTitle: "v0.2 — UI説明整理",
    devlogContent: "ステータス画面の説明文を整理し、用語を統一しました。",
    referenceUpdateSummary: "UIの説明文を整理",
  }),
  buildStagingCase({
    category: "direct",
    index: 4,
    label: "direct-04 操作感",
    voiceLabel: "操作がもっさりする",
    devlogTitle: "v0.2 — 移動速度調整",
    devlogContent: "キャラクターの移動速度を上げ、操作のもっさり感を改善しました。",
    referenceUpdateSummary: "移動速度を上げて操作感を改善",
  }),
  buildStagingCase({
    category: "direct",
    index: 5,
    label: "direct-05 セーブ",
    voiceLabel: "セーブ機能が欲しい",
    devlogTitle: "v0.2 — セーブ追加",
    devlogContent: "チェックポイントでのセーブ機能を追加しました。",
    referenceUpdateSummary: "セーブ機能を追加",
  }),
  buildStagingCase({
    category: "direct",
    index: 6,
    label: "direct-06 音量",
    voiceLabel: "BGMが大きすぎる",
    devlogTitle: "v0.2 — BGM音量",
    devlogContent: "BGMの初期音量を下げ、設定画面に音量スライダーを追加しました。",
    referenceUpdateSummary: "BGM音量を下げ設定を追加",
  }),
  buildStagingCase({
    category: "direct",
    index: 7,
    label: "direct-07 バグ修正",
    voiceLabel: "画面が固まることがある",
    devlogTitle: "v0.2 — フリーズ修正",
    devlogContent: "特定ステージで画面が固まるバグを修正しました。",
    referenceUpdateSummary: "画面フリーズバグを修正",
  }),
  buildStagingCase({
    category: "direct",
    index: 8,
    label: "direct-08 難易度選択",
    voiceLabel: "難易度選択が欲しい",
    devlogTitle: "v0.2 — 難易度追加",
    devlogContent: "イージー / ノーマルの難易度選択を追加しました。",
    referenceUpdateSummary: "難易度選択を追加",
  }),
  buildStagingCase({
    category: "direct",
    index: 9,
    label: "direct-09 マップ",
    voiceLabel: "マップが欲しい",
    devlogTitle: "v0.2 — ミニマップ",
    devlogContent: "画面右上にミニマップを追加しました。",
    referenceUpdateSummary: "ミニマップを追加",
  }),
  buildStagingCase({
    category: "direct",
    index: 10,
    label: "direct-10 文字サイズ",
    voiceLabel: "文字が小さくて読めない",
    devlogTitle: "v0.2 — 文字サイズ",
    devlogContent: "会話テキストのサイズを大きくし、設定で変更できるようにしました。",
    referenceUpdateSummary: "文字サイズを拡大し設定を追加",
  }),
  buildStagingCase({
    category: "direct",
    index: 11,
    label: "direct-11 ジャンプ",
    voiceLabel: "ジャンプが低い",
    devlogTitle: "v0.2 — ジャンプ調整",
    devlogContent: "ジャンプ力を15%上げました。",
    referenceUpdateSummary: "ジャンプ力を15%上げ",
  }),
  buildStagingCase({
    category: "direct",
    index: 12,
    label: "direct-12 ロード時間",
    voiceLabel: "ロードが長い",
    devlogTitle: "v0.2 — ロード短縮",
    devlogContent: "ステージ読み込み時間を短縮しました。",
    referenceUpdateSummary: "ロード時間を短縮",
  }),
  buildStagingCase({
    category: "direct",
    index: 13,
    label: "direct-13 キーコンフィグ",
    voiceLabel: "キー設定を変えたい",
    devlogTitle: "v0.2 — キーリマップ",
    devlogContent: "キーボードのキーリマップ機能を追加しました。",
    referenceUpdateSummary: "キーリマップ機能を追加",
  }),
  buildStagingCase({
    category: "direct",
    index: 14,
    label: "direct-14 チュートリアルスキップ",
    voiceLabel: "チュートリアルをスキップしたい",
    devlogTitle: "v0.2 — スキップ追加",
    devlogContent: "チュートリアルにスキップボタンを追加しました。",
    referenceUpdateSummary: "チュートリアルにスキップを追加",
  }),
  buildStagingCase({
    category: "direct",
    index: 15,
    label: "direct-15 敵の当たり判定",
    voiceLabel: "当たり判定が厳しい",
    devlogTitle: "v0.2 — 当たり判定",
    devlogContent: "敵の当たり判定を少し緩和しました。",
    referenceUpdateSummary: "敵の当たり判定を緩和",
  }),
  buildStagingCase({
    category: "direct",
    index: 16,
    label: "direct-16 ポーズ",
    voiceLabel: "ポーズが欲しい",
    devlogTitle: "v0.2 — ポーズ機能",
    devlogContent: "ESCキーでポーズできる機能を追加しました。",
    referenceUpdateSummary: "ポーズ機能を追加",
  }),
  buildStagingCase({
    category: "direct",
    index: 17,
    label: "direct-17 色覚",
    voiceLabel: "色だけだと区別がつかない",
    devlogTitle: "v0.2 — 色覚サポート",
    devlogContent: "色覚モード（シェイプ併用）を追加しました。",
    referenceUpdateSummary: "色覚モードを追加",
  }),
  buildStagingCase({
    category: "direct",
    index: 18,
    label: "direct-18 フレームレート",
    voiceLabel: "カクカクする",
    devlogTitle: "v0.2 — 描画最適化",
    devlogContent: "描画処理を最適化し、フレームレートの安定性を改善しました。",
    referenceUpdateSummary: "描画を最適化してカクつき改善",
  }),
  buildStagingCase({
    category: "direct",
    index: 19,
    label: "direct-19 会話スキップ",
    voiceLabel: "会話を飛ばしたい",
    devlogTitle: "v0.2 — 会話スキップ",
    devlogContent: "イベント会話にスキップボタンを追加しました。",
    referenceUpdateSummary: "会話スキップを追加",
  }),
  buildStagingCase({
    category: "direct",
    index: 20,
    label: "direct-20 自動ラン",
    voiceLabel: "ダッシュボタンが欲しい",
    devlogTitle: "v0.2 — ダッシュ追加",
    devlogContent: "Shiftキーでダッシュできる操作を追加しました。",
    referenceUpdateSummary: "ダッシュ操作を追加",
  }),
];
