import { buildStagingCase } from "./build-case";
import type { StagingLabeledCase } from "./types";

/** indirect 20 — 言葉は違うが因果が合理的 */
export const STAGING_INDIRECT_CASES: StagingLabeledCase[] = [
  buildStagingCase({
    category: "indirect",
    index: 1,
    label: "indirect-01 テンポ",
    voiceLabel: "テンポが悪い",
    devlogTitle: "v0.2 — 序盤テンポ",
    devlogContent: "序盤の待ち時間を30%短縮し、イベント発生までの間隔を詰めました。",
    referenceUpdateSummary: "序盤の待ち時間を30%短縮",
    explanationNote: "テンポ↔待ち時間の間接対応",
  }),
  buildStagingCase({
    category: "indirect",
    index: 2,
    label: "indirect-02 退屈",
    voiceLabel: "序盤が退屈",
    devlogTitle: "v0.2 — 序盤イベント",
    devlogContent: "最初のステージに小イベントを2つ追加しました。",
    referenceUpdateSummary: "序盤に小イベントを追加",
    explanationNote: "退屈↔コンテンツ追加",
  }),
  buildStagingCase({
    category: "indirect",
    index: 3,
    label: "indirect-03 難しすぎ",
    voiceLabel: "最初が難しすぎる",
    devlogTitle: "v0.2 — 初期バランス",
    devlogContent: "1面の敵出現数を減らし、初期武器の性能を上げました。",
    referenceUpdateSummary: "1面の敵出現数を減らし初期武器を強化",
  }),
  buildStagingCase({
    category: "indirect",
    index: 4,
    label: "indirect-04 分かりにくい",
    voiceLabel: "最初が分かりにくい",
    devlogTitle: "v0.2 — 導線改善",
    devlogContent: "最初の村に目的を示す矢印ガイドを追加しました。",
    referenceUpdateSummary: "目的を示す矢印ガイドを追加",
  }),
  buildStagingCase({
    category: "indirect",
    index: 5,
    label: "indirect-05 ストレス",
    voiceLabel: "プレイがストレス",
    devlogTitle: "v0.2 — チェックポイント",
    devlogContent: "各エリア入口にチェックポイントを設置しました。",
    referenceUpdateSummary: "エリア入口にチェックポイントを設置",
  }),
  buildStagingCase({
    category: "indirect",
    index: 6,
    label: "indirect-06 理不尽",
    voiceLabel: "理不尽な即死が多い",
    devlogTitle: "v0.2 — 即死トラップ",
    devlogContent: "見えにくい即死床に警告色の縁取りを追加しました。",
    referenceUpdateSummary: "即死床に警告色の縁取りを追加",
  }),
  buildStagingCase({
    category: "indirect",
    index: 7,
    label: "indirect-07 迷子",
    voiceLabel: "どこに行けばいいか分からない",
    devlogTitle: "v0.2 — クエスト更新",
    devlogContent: "クエストログに次の目的地を常時表示するようにしました。",
    referenceUpdateSummary: "クエストログに目的地を常時表示",
  }),
  buildStagingCase({
    category: "indirect",
    index: 8,
    label: "indirect-08 単調",
    voiceLabel: "戦闘が単調",
    devlogTitle: "v0.2 — 敵パターン",
    devlogContent: "序盤の敵に2種類の攻撃パターンを追加しました。",
    referenceUpdateSummary: "序盤の敵に攻撃パターンを追加",
  }),
  buildStagingCase({
    category: "indirect",
    index: 9,
    label: "indirect-09 長い",
    voiceLabel: "1ステージが長すぎる",
    devlogTitle: "v0.2 — ステージ分割",
    devlogContent: "第1章を中間セーブ地点で2区画に分割しました。",
    referenceUpdateSummary: "第1章を中間セーブ地点で分割",
  }),
  buildStagingCase({
    category: "indirect",
    index: 10,
    label: "indirect-10 情報不足",
    voiceLabel: "敵の弱点が分からない",
    devlogTitle: "v0.2 — ヒント",
    devlogContent: "ボス戦前に弱点属性のヒント会話を追加しました。",
    referenceUpdateSummary: "ボス弱点のヒント会話を追加",
  }),
  buildStagingCase({
    category: "indirect",
    index: 11,
    label: "indirect-11 入力遅延",
    voiceLabel: "操作が効かない感じがする",
    devlogTitle: "v0.2 — 入力バッファ",
    devlogContent: "ジャンプと攻撃に入力バッファ（0.12秒）を追加しました。",
    referenceUpdateSummary: "ジャンプと攻撃に入力バッファを追加",
  }),
  buildStagingCase({
    category: "indirect",
    index: 12,
    label: "indirect-12 不公平",
    voiceLabel: "敵だけ有利",
    devlogTitle: "v0.2 — 被ダメ",
    devlogContent: "被ダメージ後の無敵時間を0.3秒から0.5秒に延長しました。",
    referenceUpdateSummary: "被ダメ後の無敵時間を延長",
  }),
  buildStagingCase({
    category: "indirect",
    index: 13,
    label: "indirect-13 戻れない",
    voiceLabel: "行き止まりで詰む",
    devlogTitle: "v0.2 — ワープ",
    devlogContent: "詰みやすい穴場所にワープ石を追加しました。",
    referenceUpdateSummary: "詰みやすい場所にワープ石を追加",
  }),
  buildStagingCase({
    category: "indirect",
    index: 14,
    label: "indirect-14 読めない",
    voiceLabel: "会話が長くて疲れる",
    devlogTitle: "v0.2 — 会話短縮",
    devlogContent: "序盤NPCの会話文量を平均40%削減しました。",
    referenceUpdateSummary: "序盤NPCの会話文量を40%削減",
  }),
  buildStagingCase({
    category: "indirect",
    index: 15,
    label: "indirect-15 暗い",
    voiceLabel: "画面が見づらい",
    devlogTitle: "v0.2 — 明るさ",
    devlogContent: "洞窟ステージの環境光を上げ、プレイヤー周辺ライトを追加しました。",
    referenceUpdateSummary: "洞窟の明るさと周辺ライトを改善",
  }),
  buildStagingCase({
    category: "indirect",
    index: 16,
    label: "indirect-16 報酬",
    voiceLabel: "頑張っても報われない",
    devlogTitle: "v0.2 — 報酬調整",
    devlogContent: "隠し宝箱の報酬量を上げ、初回クリアボーナスを追加しました。",
    referenceUpdateSummary: "隠し宝箱と初回クリアボーナスを強化",
  }),
  buildStagingCase({
    category: "indirect",
    index: 17,
    label: "indirect-17 連続",
    voiceLabel: "コンボが繋がらない",
    devlogTitle: "v0.2 — コンボ猶予",
    devlogContent: "コンボ判定の猶予フレームを3Fから5Fに広げました。",
    referenceUpdateSummary: "コンボ判定の猶予を拡大",
  }),
  buildStagingCase({
    category: "indirect",
    index: 18,
    label: "indirect-18 音",
    voiceLabel: "効果音がうるさい",
    devlogTitle: "v0.2 — SE音量",
    devlogContent: "攻撃SEのピーク音量を下げ、同時再生数を制限しました。",
    referenceUpdateSummary: "攻撃SEの音量と同時再生を調整",
  }),
  buildStagingCase({
    category: "indirect",
    index: 19,
    label: "indirect-19 ソロ",
    voiceLabel: "一人だと厳しい",
    devlogTitle: "v0.2 — 支援NPC",
    devlogContent: "最初のボス戦に一時的な支援NPCを追加しました。",
    referenceUpdateSummary: "最初のボス戦に支援NPCを追加",
  }),
  buildStagingCase({
    category: "indirect",
    index: 20,
    label: "indirect-20 リトライ",
    voiceLabel: "失敗がもどかしい",
    devlogTitle: "v0.2 — リトライ",
    devlogContent: "ボス戦前から即リトライできる導線を追加しました。",
    referenceUpdateSummary: "ボス戦前から即リトライできる導線を追加",
  }),
];
