import { buildStagingCase } from "./build-case";
import type { StagingLabeledCase } from "./types";

/** reject 20 — 採用してはいけないケース */
export const STAGING_REJECT_CASES: StagingLabeledCase[] = [
  buildStagingCase({
    category: "reject",
    index: 1,
    label: "reject-01 無関係機能",
    voiceLabel: "マルチプレイが欲しい",
    devlogTitle: "v0.2 — UI整理",
    devlogContent: "インベントリUIのレイアウトを整理しました。",
    explanationNote: "voice と devlog が無関係",
  }),
  buildStagingCase({
    category: "reject",
    index: 2,
    label: "reject-02 称賛のみ",
    voiceLabel: "ゲームは面白い",
    devlogTitle: "v0.2 — バグ修正",
    devlogContent: "起動時クラッシュのバグを修正しました。",
    explanationNote: "称賛は adoption 対象外",
  }),
  buildStagingCase({
    category: "reject",
    index: 3,
    label: "reject-03 抽象devlog",
    voiceLabel: "テンポが悪い",
    devlogTitle: "v0.2 — 全体改善",
    devlogContent: "全体的に改善しました。",
    explanationNote: "抽象 summary — isAbstractUpdateSummary で reject",
  }),
  buildStagingCase({
    category: "reject",
    index: 4,
    label: "reject-04 別要素",
    voiceLabel: "BGMがうるさい",
    devlogTitle: "v0.2 — グラフィック",
    devlogContent: "背景の解像度を上げ、テクスチャを差し替えました。",
  }),
  buildStagingCase({
    category: "reject",
    index: 5,
    label: "reject-05 ストーリー",
    voiceLabel: "ストーリーが短い",
    devlogTitle: "v0.2 — 操作",
    devlogContent: "ダッシュのクールダウンを0.5秒短縮しました。",
  }),
  buildStagingCase({
    category: "reject",
    index: 6,
    label: "reject-06 対応しましたのみ",
    voiceLabel: "チュートリアルが欲しい",
    devlogTitle: "v0.2 — 対応",
    devlogContent: "要望に対応しました。",
    explanationNote: "抽象表現のみ",
  }),
  buildStagingCase({
    category: "reject",
    index: 7,
    label: "reject-07 別バージョン話題",
    voiceLabel: "エンディングが欲しい",
    devlogTitle: "v0.2 — 序盤のみ",
    devlogContent: "序盤の敵配置を変更しました。",
  }),
  buildStagingCase({
    category: "reject",
    index: 8,
    label: "reject-08 グレー弱関連",
    voiceLabel: "もう少し面白くして",
    devlogTitle: "v0.2 — 数値調整",
    devlogContent: "敵のHPを5%下げました。",
    explanationNote: "曖昧な voice — 因果が弱い",
  }),
  buildStagingCase({
    category: "reject",
    index: 9,
    label: "reject-09 販売",
    voiceLabel: "Steam版が欲しい",
    devlogTitle: "v0.2 — ゲーム内",
    devlogContent: "新ステージ「氷の洞窟」を追加しました。",
  }),
  buildStagingCase({
    category: "reject",
    index: 10,
    label: "reject-10 翻訳",
    voiceLabel: "英語対応して",
    devlogTitle: "v0.2 — 日本語のみ",
    devlogContent: "ボスAIの攻撃間隔を調整しました。",
  }),
  buildStagingCase({
    category: "reject",
    index: 11,
    label: "reject-11 反射",
    voiceLabel: "グラフィックを美化して",
    devlogTitle: "v0.2 — サウンド",
    devlogContent: "環境音を追加しました。",
  }),
  buildStagingCase({
    category: "reject",
    index: 12,
    label: "reject-12 未来予定",
    voiceLabel: "オンライン対戦",
    devlogTitle: "v0.2 — ローカル",
    devlogContent: "ローカルマルチの接続安定性を改善しました。",
    explanationNote: "オンライン要望 vs ローカル修正",
  }),
  buildStagingCase({
    category: "reject",
    index: 13,
    label: "reject-13 修正しましたのみ",
    voiceLabel: "バグがある",
    devlogTitle: "v0.2 — 修正",
    devlogContent: "修正しました。",
  }),
  buildStagingCase({
    category: "reject",
    index: 14,
    label: "reject-14 別プロジェクト話",
    voiceLabel: "前作の続編要素が欲しい",
    devlogTitle: "v0.2 — 本作",
    devlogContent: "本作の第2章を追加しました。",
  }),
  buildStagingCase({
    category: "reject",
    index: 15,
    label: "reject-15 数値のみ",
    voiceLabel: "キャラが可愛くない",
    devlogTitle: "v0.2 — ダメージ",
    devlogContent: "火属性ダメージの計算式を修正しました。",
  }),
  buildStagingCase({
    category: "reject",
    index: 16,
    label: "reject-16 可能表現",
    voiceLabel: "難しすぎる",
    devlogTitle: "v0.2 — 曖昧",
    devlogContent: "難易度改善の可能性があります。",
    explanationNote: "弱い表現パターン",
  }),
  buildStagingCase({
    category: "reject",
    index: 17,
    label: "reject-17 たぶん",
    voiceLabel: "UIが使いにくい",
    devlogTitle: "v0.2 — たぶん",
    devlogContent: "UIをたぶん改善したかもしれません。",
  }),
  buildStagingCase({
    category: "reject",
    index: 18,
    label: "reject-18 無関係バグ",
    voiceLabel: "チュートリアルが欲しい",
    devlogTitle: "v0.2 — 音声バグ",
    devlogContent: "ボイス再生が二重になるバグを修正しました。",
  }),
  buildStagingCase({
    category: "reject",
    index: 19,
    label: "reject-19 称賛+要望混在",
    voiceLabel: "好きだけど難しい",
    devlogTitle: "v0.2 — 新武器",
    devlogContent: "新武器「炎の剣」を追加しました。",
    explanationNote: "称賛混在 + 因果不明確",
  }),
  buildStagingCase({
    category: "reject",
    index: 20,
    label: "reject-20 更新しましたのみ",
    voiceLabel: "待ち時間が長い",
    devlogTitle: "v0.2 — 更新",
    devlogContent: "更新しました。",
  }),
];
