import type { DeveloperSearchResult } from "@/lib/developer-search-v0-mock-data";

/** しゃねこ（自分）のフォロワー — 開発者を探すと同型カードで表示 */
export const studioFollowersMock: DeveloperSearchResult[] = [
  {
    id: "yuki-plays",
    name: "ゆき",
    handle: "yuki_plays",
    avatar: "/images/landing/game-2.png",
    bio: "インディーRPGが好き。フィードバック多めに書くタイプです。",
    verified: false,
    isNew: false,
    inDevelopment: 0,
    completed: 0,
    followers: 42,
    genres: ["RPG", "アドベンチャー"],
    gameThumbs: [],
    following: false,
  },
  {
    id: "haruka-dev",
    name: "ハルカ",
    handle: "haruka_dev",
    avatar: "/images/landing/game-3.png",
    bio: "週末で小さなゲームを作っています。",
    verified: false,
    isNew: true,
    inDevelopment: 1,
    completed: 0,
    followers: 128,
    genres: ["パズル", "カジュアル"],
    gameThumbs: ["/images/landing/game-5.png"],
    following: false,
  },
  {
    id: "ren-voice",
    name: "レン",
    handle: "ren_voice",
    avatar: "/images/landing/game-4.png",
    bio: "見届け人として育つ過程が好き。",
    verified: false,
    isNew: false,
    inDevelopment: 0,
    completed: 0,
    followers: 89,
    genres: ["ナラティブ", "ホラー"],
    gameThumbs: [],
    following: false,
  },
  {
    id: "lunaworks",
    name: "LunaWorks",
    handle: "lunaworks",
    avatar: "/images/landing/game-3.png",
    bio: "廃墟と光をテーマに、静かな世界観を描く開発チーム。",
    verified: true,
    isNew: false,
    inDevelopment: 1,
    completed: 0,
    followers: 1820,
    genres: ["ホラー", "探索", "アドベンチャー"],
    gameThumbs: ["/images/landing/game-2.png"],
    following: false,
  },
];

export const STUDIO_FOLLOWER_COUNT = studioFollowersMock.length;
